### ISSUE TITLE
need a new name

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.Topologies#1]

**Comment by JohnMoehrke** [comment]
Note, as a whitepaper there is no need for an acronym
- Topological Federation of Document Sharing (TFDS)

**Comment by slagesse-epic** [comment]
Additional suggestions:

- Federated Document Sharing Across Complex Topologies
- Federation Across Document Sharing Communities
- Document Sharing Federation Across Heterogeneous Communities
- Bridging Heterogeneous Document Sharing Communities
- Sharing Topologies Across Layered Environments (STALE)
- Federated Environments and Sharing Topologies (FEaST)
- Document Exchange Federation Across Communities
- Document Exchange in Federated Communities Over Networks (DEFCON)
- Document Exchange Across Multi Layered Communities
- Document Exchange Federation Across Unhomogenized Layered Topologies (DEFAULT)
- Document Exchange Federated Ecosystems for Networked Sharing Environments (DEFENSE)

**Comment by oliveregger** [comment]
I would favor a combination of Federation and Document Sharing/Exchange but don't have strong opinion:
- Federation Across Document Sharing Communities
- Document Sharing Federation Across Heterogeneous Communities
- Document Exchange Federation Across Communities

**Comment by JohnMoehrke** [comment]
I think Federation is critical. I think the other critical concept is the topologies and what each style means to management and discovery. I do like the heterogeneous word / concept; as it recognizes the reality that no one topology will be used.
Im not against fun acronyms, but not self-deprecating or abusive (WTF).

**Comment by jlamy** [comment]
Federated Hops Into Responders?

Joe Lamy
Specification Expert
AEGIS.net<http://AEGIS.net>, Inc.
***@***.******@***.***>
www.aegis.net<http://www.aegis.net>

Powerful Results. Delivered.
________________________________

**Comment by slagesse-epic** [comment]
All files have been renamed.
