### ISSUE TITLE
John Comments

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.Topologies#11]
The use-case that you are trying to solve is not explained as a use-case that you are trying to solve.  I think the Use-cases are: 

1. Given that XCPD can be us to discover patients across a complex topology of federated communities and results in a patient identifier at a HCID, there is a need to understand the organization of that the HCID identifies. Descriptive, purpose, etc.
2. Given that one wants to push content directly to a given organization, there is a need to find the technical mechanism and pathway to send the content.

Note that these use-cases are very different in that one is a Query/Retrieve use-case, and another is a Push. I understand that some nationwide networks are trying to do both of these interaction models, but not everyone is.  The needs of these two use-cases are very different. in the (1) case there is no need to get technical details, in the (2) case there is no need for anything but technical details.  For someone trying to solve only one of these, they are not helped by the conflating of them.

I think you should ONLY focus on XCA (i.e. not XDS alone, or MHDS alone). That is to say your problem only exists when there are multiple Communities. You do say this in 1.1, but then go on later to cover it. I think this is true of both use-cases. A single domain can use mCSD without needing to read this whitepaper. A single domain does have a need for a degenerate form of the use-cases, but it is a far more obvious problem and a far more obvious way to solve and manage it.

The current text does not use precisely words that have meaning. "gateway" alone should never be used, only Initiating Gateway, Responding Gateway, or Initiating/Responding Gateway. Other troubling uses of words: organization, domain, community. I am especially troubled at the strange and implied use of "organization". It is sometimes meaning a data publishing organization, it sometimes is a data consuming organization, it sometimes is a business entity, it is sometimes a consulting/service organization, it is sometimes seems to be a home community id managing organization, it is sometimes an XDS Affinity Domain managing organization, etc.

The current text defines basic XDS Affinity Domain, yet uses different description and different diagrams. This is normal XDS.

The current text defines a basic XDS Affinity Domain being connected using XCA, yet uses different text description and different diagrams. This is normal XCA.

The current text defines a basic XCA connecting to a organization, yet uses different text and descriptions and different diagrams.  The ability for an organization to host XCA endpoints and not be and XDS Affinity Domain is normal XCA.

This paper should focus on topologies BEYOND these basic single XCA Community models. The use-case problem happens when the network gets bigger than the horizon, and you can't see what is beyond the horizon (to use a metaphor). I think if you simplify to BEYOND these basic single community models, then you can just use Community. I think everything ends up at HCID community idea. The fact that a Community might 'contain' multiple distinct business entities might need some mention, but essentially this is just nested communities regardless of if they are explicit, implicit, or hidden.  

Ultimately you never get to describing network topologies.  We might not need to do this except to explain that topologies for these communities of communities might be Bus Topology, Ring Topology, Star Topology, Mesh Topology, Tree Topology, but will most likely be a hybrid Topology. Getting people to understand that there is no single topology, and that all attempts to have a single kind of topology are well intended but not likely to happen as the network grows.  **THIS is why solving the use-cases is needed.**

Message Delivery -- I don't think we use this term, do we? I think what you are defining is Push. right?

**Comment by JohnMoehrke** [comment]
thanks

**Comment by JohnMoehrke** [comment]
@slagesse-epic I think you resolved all of this.. right? So it should be closed?

**Comment by slagesse-epic** [comment]
Yes, I think this should be resolved.
